// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDouSuAWPuDti-u6wjwqPxxXT3a6rMAtqE',
    appId: '1:1084398843760:web:c150100f4162db2faa41b5',
    messagingSenderId: '1084398843760',
    projectId: 'mathquiz-crozbenz',
    authDomain: 'mathquiz-crozbenz.firebaseapp.com',
    storageBucket: 'mathquiz-crozbenz.appspot.com',
    measurementId: 'G-XPEGNS8JL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMrpCi1sk22qmByNvjfNYMbtVmHJBPjLE',
    appId: '1:1084398843760:android:746984c4e2d0237faa41b5',
    messagingSenderId: '1084398843760',
    projectId: 'mathquiz-crozbenz',
    storageBucket: 'mathquiz-crozbenz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGbj7dosHnZ7Trvjxu0rroF0lZ1A4FJ5E',
    appId: '1:1084398843760:ios:375f3e1eaea3c9faaa41b5',
    messagingSenderId: '1084398843760',
    projectId: 'mathquiz-crozbenz',
    storageBucket: 'mathquiz-crozbenz.appspot.com',
    iosBundleId: 'com.example.mathCrozBenz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGbj7dosHnZ7Trvjxu0rroF0lZ1A4FJ5E',
    appId: '1:1084398843760:ios:375f3e1eaea3c9faaa41b5',
    messagingSenderId: '1084398843760',
    projectId: 'mathquiz-crozbenz',
    storageBucket: 'mathquiz-crozbenz.appspot.com',
    iosBundleId: 'com.example.mathCrozBenz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDouSuAWPuDti-u6wjwqPxxXT3a6rMAtqE',
    appId: '1:1084398843760:web:f045bd3bfd488efeaa41b5',
    messagingSenderId: '1084398843760',
    projectId: 'mathquiz-crozbenz',
    authDomain: 'mathquiz-crozbenz.firebaseapp.com',
    storageBucket: 'mathquiz-crozbenz.appspot.com',
    measurementId: 'G-8VDGC615TJ',
  );
}
